### ISSUE TITLE
Quaternion leads to segfault with -march=native

### ISSUE THREAD

**Issue by cmastalli** [stack-of-tasks/eigenpy#231] opened 2021-05-18 10:19 UTC
I have compiled eigenpy with clang-10 (Release mode) and the following flags: `-march=native -mfpmath=sse`. Then, the following code leads to a segfault:
```python
import eigenpy
eigenpy.Quaternion.Identity()
```

**Comment by nim65s** [comment] 2021-05-18 10:41
Can't reproduce.

Here are the steps I followed, on a 18.04 machine:
```bash
git clone --recursive https://github.com/stack-of-tasks/eigenpy.git
cd eigenpy
mkdir build
cd build
export CXX=/usr/bin/clang++-10
export CXX_FLAGS="-march=native -mfpmath=sse"
export=CC=/usr/bin/clang-10
cmake -DCMAKE_BUILD_TYPE=Release -DPYTHON_EXECUTABLE=/usr/bin/python3 ..
make -sj16
make test // OK
python3 -c "import eigenpy; print(eigenpy.Quaternion.Identity())"
```

As expected, I get
```
(x,y,z,w) = 0 0 0 1
```

**Comment by nim65s** [comment] 2021-05-18 10:48
ok, my `CXX_FLAGS`was wrong.

I can reproduce with
```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 689dc3d..7164e71 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -31,6 +31,7 @@ INCLUDE(cmake/ide.cmake)
 INCLUDE(cmake/apple.cmake)
 
 STRING(REPLACE "-pedantic" "" CMAKE_CXX_FLAGS ${CMAKE_CXX_FLAGS})
+set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -march=native -mfpmath=sse")
 
 # If needed, fix CMake policy for APPLE systems
 APPLY_DEFAULT_APPLE_CONFIGURATION()
 ```

Only the geometry test segfaults.

**Comment by cmastalli** [comment] 2021-05-18 10:59
> Only the geometry test segfaults.

Yes, that's correct! I also observed that `test_geometry.py` failed.

Btw, I have also similar issues with `Pinocchio.Quaternion`, but I am not sure if it is also rooted to this one.

**Comment by jcarpent** [comment] 2021-05-18 11:00
Again, please provide the version of Eigen, Boost, Python and Eigenpy you are using. Otherwise, it will be hard to provide sound help.

**Comment by jcarpent** [comment] 2021-05-18 11:02
Did you try the C++ equivalent action before opening this issue?

**Comment by cmastalli** [comment] 2021-05-18 11:09
> Again, please provide the version of Eigen, Boost, Python and Eigenpy you are using. Otherwise, it will be hard to provide sound help.

This is my setup:
  - Eigen: 3.3.7
  - Boost: 1.65.1
  - Eigenpy: devel branch
  - Ubuntu 18.04

> Did you try the C++ equivalent action before opening this issue?

No, I didn't

**Comment by jcarpent** [comment] 2021-05-18 11:33
> > Did you try the C++ equivalent action before opening this issue?
> 
> No, I didn't

Please first try this aspect and come back latter with this useful feedback.

**Comment by jcarpent** [comment] 2021-05-18 12:16
No issue on my side. 
This seems to be a conflict between different install of eigenpy.
I will close this issue as it does not seem related to eigenpy.

For future issues, you should provide a docker image replicating the issue for quick test and debugging.

**Comment by cmastalli** [comment] 2021-05-18 12:49
>  This seems to be a conflict between different install of eigenpy.

Are you sure?

This issue was reproduced by @nim65s.

I think it is too early for making that conclusion.

**Comment by jcarpent** [comment] 2021-05-18 12:56
Please start from a clean installation (e.g. Docker image) and we can discuss after that if the problem still occurs.

**Comment by cmastalli** [comment] 2021-05-18 14:21
I have no anymore the issue after cleaning up `ipython`. I realized that it was leading to segfault with `ipython` only (it was working well with `python`).

This is not exactly the @nim65s condition, but it could be a similar problem.

**Comment by jcarpent** [comment] 2021-05-18 14:22
Could you do: which python/ which ipython?

**Comment by cmastalli** [comment] 2021-05-18 14:25
> Could you do: which python/ which ipython?

No, I couldn't for ipython. But I believe it should be `/usr/bin/ipython`. Now I removed that one, I reinstalled the version using `pip install --user`.

For python, everything remains the same. So `which python` prints `/usr/bin/python`.

**Comment by cmastalli** [comment] 2021-05-18 14:26
What is the recommended approach (pip or apt install version)?

**Comment by jcarpent** [comment] 2021-05-18 14:27
The thing is that I don't think the issue is really ipython, but rather the fact that they were not based on the same version of Python.

**Comment by cmastalli** [comment] 2021-05-19 01:17
My previous comment was not correct. It still leads to segfault is your write the code using ipython console.

I have create a docker image, and I still find the same issue. You can pull the docker as `docker pull cmastalli/eigenpy-native:latest`, and the code of the Dockerfile is:
```bash
#Eigenpy image
FROM ubuntu:18.04 
MAINTAINER carlos.mastalli@gmail.com

#Set working directory
WORKDIR /home/devel

RUN apt-get update 
RUN apt-get install -y build-essential cmake python git libboost-dev python-dev python-numpy
RUN apt-get install -y libeigen3-dev
RUN apt-get install -y libboost-python-dev
RUN git clone https://github.com/stack-of-tasks/eigenpy.git eigenpy \
&& cd eigenpy \
&& git submodule update --init \
&& mkdir build \
&& cd build \
&& cmake ../ -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-march=native" \
&& make -j2 \
&& make install
ENV LD_LIBRARY_PATH="/usr/local/lib"
RUN python -c "import eigenpy; print(eigenpy.Quaternion.Identity())"
```

Unfortunately, we need to re-open this issue.

**Comment by cmastalli** [comment] 2021-05-19 08:48
solver either by #232 or #233.

I will close this issue. Thanks again @jcarpent for putting effort in providing a solution (I was getting desperate with this issue)

**Comment by cmastalli** [comment] 2021-05-19 11:36
Sorry, I need to reopen this issue as they are other problems. I will share a code that shows you which cases work and doesn't.
```python
import pinoccio
import numpy as np

t = np.array([1, 2, 3]))
q0 = pinocchio.Quaternion.Identity()
q1 = pinocchio.Quaternion.Identity()
q1.x = 1.
q3 = pinocchio.Quaternion(1, 0, 0, 0)
q4 = pinocchio.Quaternion(np.array([1, 0, 0, 0])


M0 = pinocchio.SE3(q0, t) # works!
M1 = pinocchio.SE3(q1, t) # works!

M2 = pinocchio.SE3(q2, t) # doesn't works!
M3 = pinocchio.SE3(q3, t) # doesn't works!
```

So, it seems we need to have sort of `static` constructors, right? In any case, I am not sure how this could be fixed.

**Comment by jcarpent** [comment] 2021-05-19 13:14
What is q2?
Did you recompile Pinocchio Python bindings with the same vectorization flags?
Could you update your docker image?

**Comment by jcarpent** [comment] 2021-05-19 17:12
Solved by #235.

**Comment by cmastalli** [comment] 2021-05-19 18:26
> Solved by #235.

I tested the merged PR; and unfortunately, I still find the issue from my side (in this case I used `-march=native -mfpmath=sse`.
How do you test it?

**Comment by jcarpent** [comment] 2021-05-19 19:19
Please provide a docker image. I’m already spending too much time.

**Comment by cmastalli** [comment] 2021-05-20 13:43
>  Could you update your docker image?

I have updated my docker with Pinocchio installation.
You can also see that cases without Pinocchio also leads to segfault.

**Comment by nim65s** [comment] 2021-05-21 15:21
I made [this dockerfile](https://github.com/nim65s/gepetto-utils/blob/master/docker/eigenpy/devel.Dockerfile):

```dockerfile
FROM ubuntu:focal

RUN apt-get update -y \
 && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    build-essential \
    cmake \
    git \
    libboost-all-dev \
    libeigen3-dev \
    python3-numpy \
 && rm -rf /var/lib/apt/lists/*

RUN git clone --recursive -b devel https://github.com/stack-of-tasks/eigenpy.git

WORKDIR eigenpy/build

RUN cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-march=native" -DPYTHON_EXECUTABLE=/usr/bin/python3 ..

RUN make
```

I think this is a minimal and standard way to reproduce this issue.

It can be used directly with `docker run --rm -it gepetto/utils:eigenpy-devel`, but the transfer between different computers of binaries compiled with `-march=native` is usually a bad idea.

This docker image is up-to-date with devel (on 3a7acfcc02b77d66b6c0dbe3410fb7e6dbb6b1fb, ie. with #235 merged), and running `make test` inside it shows a segfault on the `py-geometry` unit test. 

The C++ corresponding `geometry`unit-test is OK.

I was able to trigger the segfault both with GCC 9.3.10 and Clang 10, on a i5-6600 and on a i9-9900. But maybe, on other CPU families, the behavior will change, because of the `-march=native`.

**Closed** 2021-05-22 06:53 UTC

**Comment by cmastalli** [comment] 2022-02-07 13:54
Hi guys,

Sorry for bothered you again on this topic, but this issue still happens in my side, and #236 is not solving it.

@nim65s can you still reproduce the issue?

@jcarpent why is this issue closed? (we need to re-open this issue)

**Comment by jcarpent** [comment] 2022-02-07 14:05
Too many think to handle. I prefer to close it as it is me which entirely dealing with this kind of issue.

**Comment by wxmerkt** [comment] 2022-02-07 14:36
In principle, if it's a known issue that could lead to a segmentation fault, I'd leave the issue open and add something along the lines of `help wanted`.

**However, I can no longer reproduce this issue with the latest devel branch using the above modified Dockerfile on Ubuntu 20.04.** I've also run EigenPy with `-march=native` in deployment and it's been fine.

Dockerfile modified from Carlos' above (this works fine on my machine):
```docker
FROM ubuntu:20.04 
ARG DEBIAN_FRONTEND=noninteractive
#Set working directory
WORKDIR /home/devel

RUN apt-get update -qq && \
    apt-get install -y build-essential cmake python3 git libboost-dev python3-dev python3-numpy libeigen3-dev libboost-python-dev && \
    rm -rf /var/lib/apt/lists/*
RUN git clone --branch devel --recursive https://github.com/stack-of-tasks/eigenpy.git eigenpy \
&& cd eigenpy \
&& mkdir build \
&& cd build \
&& cmake ../ -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="-march=native" \
&& make -j \
&& make install
ENV LD_LIBRARY_PATH="/usr/local/lib"
ENV PYTHONPATH="/usr/local/lib/python3/dist-packages"
RUN python3 -c "import eigenpy; print(eigenpy.Quaternion.Identity())"
```

**Comment by jcarpent** [comment] 2022-02-07 14:45
Good news if it is working now. Thanks @wxmerkt to check.

**Comment by cmastalli** [comment] 2022-02-07 15:07
It is crashing with this Python code:
```python
import eigenpy; import numpy as np; print(eigenpy.Quaternion(np.eye(3)))
```

and you might need to run several times to detect the segfault.

@wxmerkt  -- can you confirm if this works or not for you?
